
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";
import { useNavigator } from "expo-router";

const Nav = createBottomTabNavigator();

export default function App() {
    // const Navigator = useNavigator(Nav)
    // return <Navigator />
    // TODO: Investigate recursive loop
    //  WARN  Please report: Excessive number of pending callbacks: 501. Some pending callbacks that might have leaked by never being called from native code: {"1274":{"module":"NativeAnimatedModule","method":"getValue"},"1279":{"module":"NativeAnimatedModule","method":"getValue"},"1290":{"module":"NativeAnimatedModule","method":"getValue"},"1333":{},"1365":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"1564":{"module":"NativeAnimatedModule","method":"getValue"},"1569":{"module":"NativeAnimatedModule","method":"getValue"},"1580":{"module":"NativeAnimatedModule","method":"getValue"},"1624":{},"1656":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"1855":{"module":"NativeAnimatedModule","method":"getValue"},"1860":{"module":"NativeAnimatedModule","method":"getValue"},"1871":{"module":"NativeAnimatedModule","method":"getValue"},"1915":{},"1947":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"2146":{"module":"NativeAnimatedModule","method":"getValue"},"2151":{"module":"NativeAnimatedModule","method":"getValue"},"2162":{"module":"NativeAnimatedModule","method":"getValue"},"2206":{},"2238":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"2437":{"module":"NativeAnimatedModule","method":"getValue"},"2442":{"module":"NativeAnimatedModule","method":"getValue"},"2453":{"module":"NativeAnimatedModule","method":"getValue"},"2497":{},"2529":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"2728":{"module":"NativeAnimatedModule","method":"getValue"},"2733":{"module":"NativeAnimatedModule","method":"getValue"},"2744":{"module":"NativeAnimatedModule","method":"getValue"},"2788":{},"2820":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"3019":{"module":"NativeAnimatedModule","method":"getValue"},"3024":{"module":"NativeAnimatedModule","method":"getValue"},"3035":{"module":"NativeAnimatedModule","method":"getValue"},"3079":{},"3111":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"3310":{"module":"NativeAnimatedModule","method":"getValue"},"3315":{"module":"NativeAnimatedModule","method":"getValue"},"3326":{"module":"NativeAnimatedModule","method":"getValue"},"3370":{},"3402":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"3601":{"module":"NativeAnimatedModule","method":"getValue"},"3606":{"module":"NativeAnimatedModule","method":"getValue"},"3617":{"module":"NativeAnimatedModule","method":"getValue"},"3661":{},"3693":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"3892":{"module":"NativeAnimatedModule","method":"getValue"},"3897":{"module":"NativeAnimatedModule","method":"getValue"},"3908":{"module":"NativeAnimatedModule","method":"getValue"},"3952":{},"3984":{"module":"NativeAnimatedModule","method":"startAnimatingNode"},"...(truncated keys)...":451} 
    return null;
}
