name: "\U0001F41B Bug Report (MOVED TO expo/expo)"
description: "Expo Router has moved repos and issues should no longer be opened here."
body:
  - type: markdown
    attributes:
      value: The source code for Expo Router has moved upstream to the [expo/expo](https://github.com/expo/expo/tree/main/packages/expo-router) repo, please open new issues here [Expo Router Bug Report](https://github.com/expo/expo/issues/new?template=bug_report_router.yml). Learn more about the [`expo-router` source migration](https://github.com/expo/router/discussions/820).