blank_issues_enabled: false
contact_links:
  - name: Open an Expo Router issue
    url: https://github.com/expo/expo/issues/new?template=bug_report_router.yml
    about: Open issues for Expo Router in the expo/expo repo.
  - name: Expo Developers Discord
    url: https://chat.expo.dev/
    about: Join other developers in discussions regarding Expo.
