// import { Image } from "expo-image";

import Image from "@/components/img";
import React, { useMemo } from "react";
import { A } from "@expo/html-elements";
import Head from "expo-router/head";
import { StyleSheet } from "react-native";

import { useFonts, Inter_500Medium } from "@expo-google-fonts/inter";

import styles from "@/styles/Home.module.css";

const inter = { fontFamily: "Inter_500Medium" };

export default function App() {
  useFonts({ Inter_500Medium });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={styles.main}>
        <div style={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code style={styles.code}>pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                source={{ uri: "/vercel.svg" }}
                alt="Vercel Logo"
                style={styles.vercelLogo}
                width={100}
                height={24}
                priority={"high"}
              />
            </a>
          </div>
        </div>

        <div style={styles.center}>
          <Image
            style={styles.logo}
            source="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority={"high"}
          />
          <div style={styles.thirteen}>
            <Image
              source="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority={"high"}
            />
          </div>
        </div>

        <div style={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            style={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 style={inter}>
              Docs <span>-&gt;</span>
            </h2>
            <p style={inter}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            style={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 style={inter}>
              Learn <span>-&gt;</span>
            </h2>
            <p style={inter}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            style={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 style={inter}>
              Templates <span>-&gt;</span>
            </h2>
            <p style={inter}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            style={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 style={inter}>
              Deploy <span>-&gt;</span>
            </h2>
            <p style={inter}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}

const vars = {
  "--max-width": "1100px",
  "--font-mono": `ui-monospace, Menlo, Monaco, 'Cascadia Mono', 'Segoe UI Mono',
  'Roboto Mono', 'Oxygen Mono', 'Ubuntu Monospace', 'Source Code Pro',
  'Fira Mono', 'Droid Sans Mono', 'Courier New', monospace`,
};

// const styles = StyleSheet.create({
//   main: {
//     justifyContent: "space-between",
//     alignItems: "center",
//     padding: "6rem",
//     minHeight: "100vh",
//   },
//   card: {},
//   vercelLogo: {},
//   center: {},
//   description: {
//     // display: inherit;
//     justifyContent: "space-between",
//     alignItems: "center",
//     fontSize: "0.85rem",
//     maxWidth: vars["--max-width"],
//     width: "100%",
//     zIndex: 2,
//     fontFamily: vars["--font-mono"],
//   },
//   code: {
//     fontWeight: "700",
//     fontFamily: vars["--font-mono"],
//   },
//   grid: {},
//   logo: {},
//   thirteen: {},
// });

// TODO: inherit from the parent
