import Image from "@/components/img";
import React, { useMemo } from "react";
import Head from "expo-router/head";

import { useFonts, Inter_500Medium } from "@expo-google-fonts/inter";
import createElement from "react-native-web/dist/exports/createElement";

import styles from "@/styles/Home.module.css";

const inter = { fontFamily: "Inter_500Medium" };

const P = (props) => createElement("p", props);
const Code = (props) => createElement("code", props);
const Img = (props) => createElement("img", props);

export default function App() {
  useFonts({ Inter_500Medium });
  console.log("styles", styles);
  return (
    <div style={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={styles.main}>
        <div style={styles.description}>
          <P>
            Get started by editing&nbsp;
            <Code style={styles.code}>pages/index.js</Code>
          </P>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Img
                src="/vercel.svg"
                // source={{ uri: "/vercel.svg" }}
                alt="Vercel Logo"
                style={styles.vercelLogo}
                width={100}
                height={24}
                priority={"high"}
              />
            </a>
          </div>
        </div>

        <div style={styles.center}>
          <Img
            style={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority={"high"}
          />
          <div style={styles.thirteen}>
            <Img
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority={"high"}
            />
          </div>
        </div>

        <div style={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            style={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 style={inter}>
              Docs <span>-&gt;</span>
            </h2>
            <P style={inter}>
              Find in-depth information about Next.js features and&nbsp;API.
            </P>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            style={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 style={inter}>
              Learn <span>-&gt;</span>
            </h2>
            <P style={inter}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </P>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            style={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 style={inter}>
              Templates <span>-&gt;</span>
            </h2>
            <P style={inter}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </P>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            style={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 style={inter}>
              Deploy <span>-&gt;</span>
            </h2>
            <P style={inter}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </P>
          </a>
        </div>
      </main>
    </div>
  );
}
