name: E2E Test Packages
on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18"]
    name: Build with Node ${{ matrix.node }}
    steps:
      - name: 🏗 Setup repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: 📦 Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: 👷 Build packages
        run: yarn lerna run prepare --stream

      # - name: 🚨 Lint Docs app
      #   run: yarn lint --max-warnings 0

      - name: ♻️ Store build artifacts
        uses: actions/cache@v3
        with:
          path: "*"
          key: v3-${{ github.sha }}-${{ matrix.node }}

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        node: ["18"]
        package: [expo-router]
    name: Test ${{ matrix.package }} on Node ${{ matrix.node }}
    steps:
      - name: ♻️ Restore build artifacts
        uses: actions/cache@v3
        with:
          path: "*"
          key: v3-${{ github.sha }}-${{ matrix.node }}

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: 🧪 Test ${{ matrix.package }}
        run: yarn test:e2e
        working-directory: packages/${{ matrix.package }}
        env:
          EXPO_DEBUG: true
